h1("4.  Input parameters, prompt and output parameters"),
small("Revised 21 September 2026. This section describes the run currently in use: one tag per conversation, every content-bearing column as input, and the whole 73-tree topic tree as the target. Sections 5 to 9 still describe the earlier per-exchange CBSE-only run and are marked where they differ."),
p("Classification is one model call per conversation. This section gives it as a contract: what goes in, what is sent, and what comes back."),

/* ---------------- 4.1 INPUT ---------------- */
h2("4.1  Input parameters"),
p("Nine parameters, assembled once per conversation. Seven come from the two ShowNAsk tables; grade, board and target are joined in from the central student profile on ", ["user_id", false, true], "."),
table(["#", "Parameter", "Source column", "Present on"],
  [["1", "user_id", "conversations.user_id", "271 / 271"],
   ["2", "conversation_id", "conversations.conversation_id", "271 / 271"],
   ["3", "what was the input", "conversation_turns.input_parts\nwhere kind = 'text'", "219 / 271"],
   ["4", "what did the bot respond", "conversation_turns.response.text\nand .md", "271 / 271"],
   ["5", "prior recent coverage\n(student side)", "prior_coverage_recent.student", "214 / 271"],
   ["6", "prior recent coverage\n(delivered side)", "prior_coverage_recent.delivered", "245 / 271"],
   ["7", "prior coverage older\ndelivered", "prior_coverage_older_delivered", "62 / 271"],
   ["8", "grade", "analytics_rag.student.grade", "271 / 271"],
   ["9", "board / target", "analytics_rag.student.board\nanalytics_rag.student.target", "271 / 271"]],
  [560, 2400, 3600, 2800], { mono: [1, 2] }),
gap(),
p(["The profile join is what makes parameters 8 and 9 complete.", true], " Taken from the conversation itself, grade was missing on 46 conversations, board on 56 and target on 47, and the values were free text with seventeen spellings of the board. Taken from the profile, all 271 carry all three and the values are closed enumerations. The two disagree on grade for 19 conversations; the profile is usually the one that matches the content."),
p(["One limit worth stating.", true], " The profile board is a seven-value enumeration - CBSE, ICSE, STATE, MAHARASHTRA, IB, OTHERS, NA - and does not say ", ["which", false, true], " state. For 119 of 271 conversations the board names no tree at all, and the CBSE and NCERT backbone carries them. The board captured on the conversation keeps the specific value (BIEAP, BSE Telangana, MH) and is used as a fallback where the profile is generic."),
gap(),

h3("Deliberately excluded"),
table(["Column", "Why it is not an input"],
  [["text, image", "Empty on all 2,517 turns of the day. The content lives in input_parts and response."],
   ["metadata_title", "A bare timestamp on all 271 - \"Conversation 2026-09-20 08:11 UTC\". No topic signal."],
   ["prior_coverage_\nolder_student", "The student side of the running summary. Dropped to keep the parameter set to nine; it repeats what the delivered side already covers."],
   ["state_user_stream,\nstate_user_examTargets", "Dropped with the same reasoning. Removing them moved 12 of 241 tree assignments, all state-board students falling back to CBSE."],
   ["user_id name fields,\nstate_user_role", "Identity, not topic."],
   ["state_current_image,\n_source", "Empty on all 271."],
   ["id, dpt_*, source,\nclient_info_*", "Pipeline plumbing."],
   ["feedback table\n(40 columns)", "Rates the answer; does not state the topic. Useful for quality work, not for tagging."]],
  [2600, 6760], { mono: [0] }),
pb(),

/* ---------------- 4.2 PROMPT ---------------- */
h2("4.2  The prompt"),
p("Sent verbatim as the system block, ahead of the candidate list:"),
...code(PROMPT_V3),
gap(),
p(["Three rules carry most of the weight.", true], " Tag what was taught rather than what was asked, because the two diverge often. Where notes and response disagree, the notes win - they are the bot's considered summary, the response is one turn of talk. And the candidate list is ranked by the student's profile but never limited to it."),
pb(),

/* ---------------- 4.3 CANDIDATES ---------------- */
h2("4.3  The candidate list"),
p("The whole tree is in scope: 73 trees, 42,476 nodes, 4,463 chapter rows collapsing to 2,032 distinct subject-and-chapter concepts. The student's grade, board and target ", ["rank", false, true], " that list; they do not cut it."),
p(["Why ranking and not filtering.", true], " Both were measured on the same 241 tagged conversations:"),
table(["Treatment", "Conversations that reach their own tag", "Share"],
  [["Filter - only the student's own trees", "191 of 241", "79.3%"],
   ["Rank - full tree stays reachable", "241 of 241", "88.9%"]],
  [4000, 3560, 1800], { numeric: [2] }),
gap(),
p("Filtering loses 50 conversations, and the losses are ordinary student behaviour rather than tagging error: ten grade-12 state-board students on Probability Distributions, a chapter that exists only in the Tamil Nadu tree their profile cannot name; four grade-11 JEE students revising class-10 Polynomials; three grade-8 students on complex numbers. Across the day, ", ["85.5% of conversations sit in the student's own grade, 8.7% run above it and 5.8% below", true], ". A candidate list bound to the profile discards that 14.5%."),
gap(),

h3("Tree selection, in order"),
table(["Rank", "Rule"],
  [["1", "A tree whose family matches the declared board and whose grade band contains the student's grade."],
   ["2", "A tree whose family matches the exam target (JEE, NEET, Foundation, Olympiad) and whose band contains the grade."],
   ["3", "The CBSE or NCERT tree for that grade band."],
   ["4", "Any tree whose band contains the grade."],
   ["5", "The tree whose band sits closest at or below the grade, CBSE and NCERT preferred."]],
  [900, 8460]),
gap(),
small("The five unnamed trees - 2,202 nodes with no entry in cmdsquestiontagging, three of them near-identical grade-10 clones - are excluded from selection at every rank. Left in, they outrank real trees for grade-10 students and pull class-11 physics into an orphan."),
pb(),

/* ---------------- 4.4 OUTPUT ---------------- */
h2("4.4  Output parameters"),
p("One row per conversation, written to ", ["topic_mapping.csv", false, true], ". The prompt's own output line is the middle five fields; the rest are joined back deterministically."),
table(["Column", "Type", "Values and meaning"],
  [["user_id", "string", "Carried through from the input."],
   ["conversation_id", "string", "Carried through. The primary key of the file."],
   ["grade, board, target", "string", "The profile values that ranked the candidate list, kept so any row can be re-judged without re-joining."],
   ["exchanges", "integer", "How many questions the conversation contained."],
   ["subject", "string", "A subject name from the tree, or one of three refusals:\nNOT_ACADEMIC - chit-chat, app questions, a photo with no question\nOUT_OF_SCOPE - real academics no chapter covers\nUNKNOWN - nothing legible to go on"],
   ["chapter", "string", "The chapter name, copied exactly from the tree. On a refusal row this holds the reason instead."],
   ["chapter_id", "string", "24-character chapter id. Empty on a refusal row."],
   ["topic", "string", "The exact node name inside that chapter, or CHAPTER_ONLY when the chapter is right but no node inside it fits."],
   ["topic_id", "string", "24-character node id. Empty when topic is CHAPTER_ONLY."],
   ["topic_level", "enum", "TOPIC | SUB_TOPIC. How deep into the tree the tag reached."],
   ["tree", "string", "Which of the 73 trees carries the chosen chapter - 10_CBSE, 11_12_JEE, 12_Tamilnadu."],
   ["confidence", "enum", "HIGH - the notes name the chapter's content outright\nMED - inferred from worked examples or the student's own words\nLOW - a guess"],
   ["note", "string", "Free text, written only where the call was not clean: a conversation spanning two chapters, a chapter borrowed from another board, a grade that contradicts the content."]],
  [2200, 1200, 5960], { mono: [0, 1] }),
gap(),

h3("What the run produced"),
table(["Outcome", "Conversations", "Share"],
  [["Tagged to a chapter", "241", "88.9%"],
   ["  of those, to an exact topic node", "232", "85.6%"],
   ["  of those, chapter only - no node fits", "9", "3.3%"],
   ["Not academic", "15", "5.5%"],
   ["Not in the tree", "13", "4.8%"],
   ["Nothing to go on", "2", "0.7%"]],
  [4600, 2560, 2200], { numeric: [1, 2] }),
gap(),
p("232 exact topics across 156 distinct nodes, 108 chapters and 21 trees. Confidence on the 241: 185 high, 53 medium, 3 low."),
pb(),

/* ---------------- 4.5 HOW IT RAN ---------------- */
h2("4.5  How this was executed"),
p(["The script exists and is complete, but it was not the thing that ran.", true], " ", ["tag.py", false, true], " needs an Anthropic API key, which was not available. Every tag reported here was produced by following the prompt above by hand, against the same candidate lists, with the same validity check: any subject-and-chapter pair not present in the tree is rejected. Zero invalid pairs survived into the output."),
p(["This remains the single largest caveat in the document.", true], " These numbers describe what the method produces when followed carefully by one reader, not what an unattended pipeline produces. The two should be expected to differ."),
p(["Accuracy has not been measured.", true], " 88.9% and 85.6% are coverage - the tag landed on a real node - not correctness. No human-labelled reference set exists. A 60-conversation blind labelling pack has been prepared for two subject leads to fill in independently; scoring it gives chapter agreement, topic agreement, and the human-versus-human ceiling that says whether a disagreement is a tagging error or an ambiguity in the tree."),
pb(),
